# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: oraclejdk9

# Improve Build Speed https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
    - $HOME/.m2
script: "mvn cobertura:cobertura"


after_success:
    - bash <(curl -s https://codecov.io/bash)
# Notifications https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    recipients:
      - alexandrovkirillv@gmail.com
    on_success: always # default: change
    on_failure: always # default: always






